### ISSUE TITLE
Unclear relation between tags and crate versions

### ISSUE THREAD

**Issue by wentasah** [castelao/GSW-rs#64]
What is the relation between the crate version (currently 0.1.4) and tags in this repo (currently 0.0.11)?

**Comment by castelao** [comment]
My bad, I fell behind. I wasn't taking it too serious since it is still `0.x`, but no excuse. I used in the past auto release/publish with CI, but now I have mixed feelings about that. How do you yourself? Do you publish to crates.io manually?

I just tagged the [v0.1.4](https://github.com/castelao/GSW-rs/releases/tag/v0.1.4), and I'll do a better job on that now on.

Thanks for raising the issue!

**Comment by wentasah** [comment]
I don't have any crate published on crates.io so I cannot really comment on the best way to do releases. I'd probably start with manual publishing and if that is too tedious, I'd automate it with scripts/Makefiles/...

**Comment by castelao** [comment]
@wentasah , thanks! I'll keep it sync between GitHub releases and crates.io manually for now.

I'm closing this issue, but if I'm missing anything, please let me know.

Thank you for your time!
